services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mvp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./infra/initdb:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    depends_on: [db]
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/mvp
    ports: ['4000:4000']

  frontend:
    build: ./frontend
    depends_on: [backend]
    environment:
      - BACKEND_URL=http://backend:4000
    ports: ['3000:3000']

volumes:
  db-data:
